name: thesis
channels:
    - defaults
    - pytorch
    - conda-forge
    - districtdatalabs
dependencies:
    - seaborn
    - matplotlib
    - wordcloud
    - joypy
    - numpy
    - pytorch=1.11.0
    - torchtext
    - spacy
    - ignite
    - torchmetrics
    - cudatoolkit
    - jupyterlab
    - ipywidgets
    - pytest
    - tqdm
    - sentence-transformers
    - coverage-badge
    - requests
    - yellowbrick
    - scikit-learn-extra
    - statsmodels
    - pip
    - pip:
        - pytorch-common==0.1.2

         # Required to fix a dependency error. Remove when error being fixed.
        - wrapt

         # Required to fix next tqdm issue: 
         # Failed to load model class 'HBoxModel' from module '@jupyter-widgets/controls.
        - jupyterlab-widgets==1.1.1
        - ipywidgets==7.7.2