name: thesis
channels:
    - defaults
    - pytorch
    - conda-forge
    - districtdatalabs
dependencies:
    - seaborn
    - matplotlib
    - wordcloud
    - joypy
    - numpy
    - pytorch=1.11.0
    - torchtext
    - spacy
    - ignite
    - torchmetrics
    - cudatoolkit
    - jupyterlab
    - ipywidgets
    - pytest
    - tqdm
    - sentence-transformers
    - coverage-badge
    - requests
    - yellowbrick
    - scikit-learn-extra
    - statsmodels
    - pip
    - pip:
        - pytorch-common==0.1.0
        - wrapt # Required to fix a dependency error. Remove when error being fixed.
