name: thesis

channels:
    - defaults
    - pytorch
    - conda-forge
    - districtdatalabs

dependencies:
    - seaborn
    - matplotlib
    - wordcloud
    - joypy
    - numpy
    - pytorch=1.11.0=py3.10_cuda11.5_cudnn8.3.2_0 
    - torchtext
    - torchmetrics
    - spacy
    - ignite
    - jupyterlab
    - ipywidgets
    - tqdm
    - coverage-badge
    - requests
    - yellowbrick
    - scikit-learn-extra
    - statsmodels
    - pip
    - pip:
        - pytorch-common==0.1.2
        - singleton-decorator
        - chromadb
        - sentence-transformers

        # Required to fix next tqdm issue: 
        # Failed to load model class 'HBoxModel' from module '@jupyter-widgets/controls.
        - ipywidgets
