name: thesis

channels:
    - defaults
    - conda-forge
    - districtdatalabs

dependencies:
    - cxx-compiler
    - seaborn
    - matplotlib
    - wordcloud
    - joypy
    - numpy
    - spacy
    - jupyterlab
    # Required to fix next tqdm issue:
    # Failed to load model class 'HBoxModel' from module '@jupyter-widgets/controls.
    - ipywidgets
    - tqdm
    - coverage-badge
    - requests
    - yellowbrick
    - scikit-learn-extra
    - statsmodels
    - pytest
    - pip
    - pip:
        - torch
        - ignite
        - torchtext
        - torchmetrics
        - pytorch-common
        - singleton-decorator
        - chromadb
        - sentence-transformers
        - scikit-surprise