name: thesis
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - seaborn
  - matplotlib
  - wordcloud
  - joypy
  - numpy
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - jupyterlab
  - pytest
  - pip
  - pip:
     - pykeops
     - pytorch-common==0.0.19
