name: thesis
channels:
  - defaults
  - pytorch
  - conda-forge
  - rapidsai
dependencies:
  - seaborn
  - matplotlib
  - wordcloud
  - joypy
  - numpy<=1.21
  - cudf
  - pytorch
  - cudatoolkit
  - jupyterlab
  - pymongo
  - dtale
  - pip
  - pip:
    - pytorch-common>=0.0.16
