name: thesis

channels:
    - defaults
    - conda-forge
    - districtdatalabs

dependencies:
    - bunch
    - seaborn
    - matplotlib
    - wordcloud
    - joypy
    - numpy
    - spacy
    - jupyterlab
    # Required to fix next tqdm issue:
    # Failed to load model class 'HBoxModel' from module '@jupyter-widgets/controls.
    - ipywidgets
    - tqdm
    - coverage-badge
    - requests
    - yellowbrick
    - scikit-learn-extra
    - statsmodels
    - pytest
    - optuna
    - mysqlclient
    - pip
    - pip:
          - --extra-index-url https://download.pytorch.org/whl/cu118
          - torch
          - ignite
          - torchtext
          - torchmetrics==0.11.4
          - pytorch-common
          - singleton-decorator
          - chromadb
          - sentence-transformers
          - scikit-surprise
          
