from .profiles_handler import profiles_handler
from .recommendations_handler import recommendations_handler
from .chat_histories_handler import chat_histories_handler
from .interactions_handler import interactions_handler
from .items_handler import items_handler
from .recommenders_handler import recommenders_handler